### ISSUE TITLE
Cannot create Linux Cluster in Module 6 of workshop

### ISSUE THREAD

**Issue by susanibach** [MSFTImagine/computerscience#10]
Workshop 
Lab 6 HPC
Creating and Using a SLURM Cluster
Exercise 1 - Create a SLURM cluster using an Azure QuickStart template
Step 4  fails with the following error message when you try to deploy

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentFailed)
The platform image 'Canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)
The platform image 'Canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)
The platform image 'Canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)

**Comment by jeffprosise** [comment]
This was fixed several months ago. Sorry it took me so long to review and close it!
