### ISSUE TITLE
Workshop Lab 6 cannot complete the lab

### ISSUE THREAD

**Issue by demoaccount11** [MSFTImagine/computerscience#11]
Workshop 
 Lab 6 HPC
 Creating and Using a SLURM Cluster
 Exercise 1 - Create a SLURM cluster using an Azure QuickStart template
 Step 4 fails with the following error message when you try to deploy

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentFailed)
 The platform image 'Canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)
 The platform image 'Canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)
 The platform image 'Canonical:UbuntuServer:15.10:latest' is not available. Verify that all fields in the storage profile are correct. (Code: ImageNotFound)

**Comment by jeffprosise** [comment]
In Exercise 1, Step 2, be sure to change ubuntuOSVersion to 16.04.0-LTS. I will change the screen shot to make that clearer.
