### ISSUE TITLE
Activating Azure - offer walkthrough for Visual Studio Dev Essentials too

### ISSUE THREAD

**Issue by neaorin** [MSFTImagine/computerscience#26]
Module 1 Lesson 1 Activating your Azure Pass and Using the Azure Portal Lab 

this HOL only describes the process of activating an Azure Pass (which are only valid for 30 days). 
Since we introduced Visual Studio Dev Essentials (https://www.visualstudio.com/dev-essentials/) which comes with $25 of free Azure for one year, it would be useful to describe the process of activating an Azure subscription through this offering.

**Comment by susanibach** [comment]
Since we are primarily using these workshops with students we didn't want to focus on Azure offers that require a credit card.  So it was a conscious decision to leave off descriptions of Dev Essentials and the Azure Free Trial in the instructions.  If you feel strongly about it feel free to disagree and explain your perspective.

**Comment by neaorin** [comment]
Hi Susan,

Thanks for your answer. My reasoning is based on the following points:

1. Azure Passes are only valid for 30 days, and most (all?) of the course modules would take longer to schedule and teach on a real academic setup.
2. You can only use one Azure Pass for your Microsoft account ([as explained here](https://azure.microsoft.com/en-us/offers/azure-pass/) in the FAQ). A new pass would require you to create a new Microsoft account. You'd also be losing access to your previously created resources, which might be useful to refer to later in your module, or to refresh your knowledge.
3. By contrast, the VS Dev Essentials package has some Azure credit (currently $25 a month) which is valid for an entire year. It is true that requiring a CC can be a limiting factor for students, which is why I would propose to add it as an alternative to the Azure Pass.  
4. The Microsoft Imagine (formerly DreamSpark) would be a good choice in terms of length and not requiring a CC, but the number of available Azure services is too limited right now.

**Comment by susanibach** [comment]
Where are you planning to use the workshop content?

**Comment by shanamatthews** [comment]
@neaorin and @susanibach - I agree with your reasoning for not including the Dev Essentials credit, but I think now that we have the Azure for Students credits available, it would be great to highlight that instead. 
Let me know if either of you disagree!
