### ISSUE TITLE
Building Smart Apps with Azure Machine Learning - application.ts needs to add "Data source URL" in globalParameters

### ISSUE THREAD

**Issue by salman1993** [MSFTImagine/computerscience#36]
Building Smart Apps with Azure Machine Learning workshop: https://github.com/MSFTImagine/computerscience/blob/master/Workshop/4.%20Machine%20Learning/Azure%20Machine%20Learning%20HOL%20(Node).md

In Exercise 6, Step 17 - some code is given for application.ts file. The Data source URL is not given and the server responds Bad Argument to requests. I have fixed the code in my local machine and this seems to work.

```
submitGrid() {
...

        const url = 'web_url';
        /** The Data source URL needs to be added */
        let request = { ...
            },
            globalParameters: {
                "Data source URL": url
            }
        };
}
```

**Comment by susanibach** [comment]
Hi Salman,
The instructions in the lab Exercise 5 Step 7, tell you where to retrieve the URL you should specify as the web url and API Key.  Then in Exercise 6 Step 18 they tell you do update those values.  I just ran through the lab myself and it seems to be working as long as you copy over that URL and API key.  Hope that helps! Susan
