### ISSUE TITLE
LUIS tutorial needs an update

### ISSUE THREAD

**Issue by MohamedSahbi** [MSFTImagine/computerscience#38]
The interface of cognitive services (especially LUIS) has changed. 
Starting from step 6 in the Exercise 3 (Add pre-built entities and phrase lists), it is not possible to add parameters to an Intent.

**Comment by shanamatthews** [comment]
Closing out old feedback. Jeff and the team tries to keep labs as up-to-date as possible. I believe the LUIS lab has been updated since May, but if it's still an issue, let us know! Azure changes so fast, we appreciate the heads up when things need fixed 👍
