### ISSUE TITLE
PowerBI dashboard : problem with the credentials

### ISSUE THREAD

**Issue by MohamedSahbi** [MSFTImagine/computerscience#39]
I couldn't connect to the server with the given credentials. 
( I tried to connect using different devices and accounts)
<img width="960" alt="screenshot 1078" src="https://cloud.githubusercontent.com/assets/25180044/25993202/8b658ba0-3709-11e7-850e-2c7666e995ff.png">

**Comment by shanamatthews** [comment]
Closing out old feedback - I hope this got resolved!
