### ISSUE TITLE
HDInsight Hadoop HOL: Login password mismatch

### ISSUE THREAD

**Issue by hc825b** [MSFTImagine/computerscience#45]
First I want to thank you all for providing such great Hands-on-Labs for Azure!

I followed your Hadoop HOL and found a mismatch on the login password.
In Exercise 1 Step 3 the guide says to set cluster login password to "Azure4Research!",
but later in Exercise 2 Step 1 the guide uses "Had00pdemo!" as the password to login through SSH.
It's trivial but still took me quite a few minutes to find this out.

Chiao

**Comment by jeffprosise** [comment]
Thanks for letting me know! I will fix this ASAP.


  *   Jeff
