### ISSUE TITLE
Use @Azure Cloud Shell in lab exercises instead of putty.

### ISSUE THREAD

**Issue by irwinwilliams** [MSFTImagine/computerscience#46]
Hey,
I was just going through Module 4 Lesson 03 before I used it in class.
Part of it requires SSH. For this kind of stuff, putty is the goto tool. But with the advent of Azure Cloud Shell, the same commands can be issued directly on the azure portal instead of with a separate tool to download/install.
So, I'm recommending that we use that instead.

**Comment by jeffprosise** [comment]
I agree, and will test it and put that change in the queue. Thanks!

**Comment by dotnetgator** [comment]
Well, that’s nice timing.

**Comment by shanamatthews** [comment]
I believe Jeff went ahead and made these changes where possible. Yay cloud shell! 😃
