### ISSUE TITLE
Should we create a research.md?

### ISSUE THREAD

**Issue by irwinwilliams** [MSFTImagine/computerscience#51]
It seems like a good idea to create a space for tracking relevant research based on the modules presented.
It may be that the research represents further exploration of the topics that are discussed and might give ideas as to how the technology can be used.
Thus, I'm proposing something like, "Research.MD" where you can add that and relate it in the course content.
I'm currently looking at the IoT module and a few examples of research look good to add.

**Comment by joshuajosh59** [comment]
i feel this might be a good idea!

**Comment by shanamatthews** [comment]
Hmmm - neat idea! If you're still excited about it, feel free to fork the repo and make a PR 👍
