### ISSUE TITLE
Blockchain workshop

### ISSUE THREAD

**Issue by leestott** [MSFTImagine/computerscience#52]
Users getting error on contact deployment 

Using network 'development'.

Running migration: 1_initial_migration.js
 Deploying Migrations...
 ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: exceeds block gas limit
   at Object.InvalidResponse (C:\soft\nvm\v6.8.1\node_modules\truffle\build\cli.bundled.js:43303:16) 

The issue seems to be the information doesn't call out the requirement for a , 

the code should look like 

Code should look something like..
network_id: "*",
     gas: 4600000 

Missing the , causes this issue/error so its good to call this out in the workshop

**Comment by jeffprosise** [comment]
Is this in Exercise 5?

**Comment by leestott** [comment]
Jeff yes.

**Comment by shanamatthews** [comment]
thanks Lee & Jeff - probably safe to assume this got fixed!
