### ISSUE TITLE
Stage number 21 not working

### ISSUE THREAD

**Issue by krupers** [MSFTImagine/computerscience#76]
Workshop "Handling Big Data with Azure Data Lake".

While performing actions described in stage 21:

"Now execute the following commands to create a Data Lake catalog credential used to authenticate when executing federated queries. Substitute your Data Lake Analytics account name for ANALYTICS_ACCOUNT_NAME, your database server name (the one specified in Step 11 of this exercise) for DATABASE_SERVER_NAME, and the database server user (also specified in Step 11) for DATABASE_USER:" (number 21) there is an issue while using this command.

and later:

"az dla catalog credential create --account ANALYTICS_ACCOUNT_NAME --database-name UserIntegration --uri tcp://DATABASE_SERVER_NAME.database.windows.net --credential-name FederatedCredential --user-name DATABASE_USER"

Only two people performed it without any problems. What is the correct solution?

Users (students) have Azure Pass subscription, but this also not working on a Azure Students subscription.

Elevating first command:
**"az config mode arm"**

gives an error:
**"az: error: argument _command_package: invalid choice: config"**

Elevating second command:
**"az dla catalog credential create --account ANALYTICS_ACCOUNT_NAME --database-name UserIntegration --uri tcp://DATABASE_SERVER_NAME.database.windows.net --credential-name FederatedCredential --user-name DATABASE_USER"**

gives an error:
**A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the host name 'SOME_NUMERICAL_VALUE'
Could not retrieve token from local cache.**

**Comment by shanamatthews** [comment]
Note for Shana: https://docs.microsoft.com/en-us/cli/azure/dla/catalog/credential?view=azure-cli-latest

**Comment by shanamatthews** [comment]
Okay - it looks like there are 2 issues here:
1. This step was improperly updated for CLI 2.0 ("az config mode arm" isn't a real command anymore since CLI 2.0 _only_ works with Resource Manager-based resources.)
2. There's some kind of bug in Cloud Shell with credential management... I'll see if I can get this routed to the right people :)
